// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-cyberpunk/Cyberpunk.tsx": () => import("../components/mockups/portfolio-cyberpunk/Cyberpunk.tsx"),
  "./components/mockups/portfolio-minimalist/Minimalist.tsx": () => import("../components/mockups/portfolio-minimalist/Minimalist.tsx"),
  "./components/mockups/portfolio-neural/Neural.tsx": () => import("../components/mockups/portfolio-neural/Neural.tsx")
};
